### ISSUE TITLE
Pesquisa sobre Strava, RunKeeper e Nike Run Club

### ISSUE THREAD

**Issue by mlutegar** [mlutegar/PBE-GRUPO-MMA#1]
Realizar uma pesquisa detalhada sobre os aplicativos **Strava**, **RunKeeper** e **Nike Run Club**. O objetivo é identificar e destacar as principais funcionalidades de cada um desses aplicativos. A pesquisa deve incluir, mas não se limitar a:

- Funcionalidades principais (monitoramento de atividades, integração com dispositivos, social features, etc.).
- Diferenciais em relação a outros aplicativos do mercado.
- Usabilidade e interface do usuário.
- Opções de personalização e configuração.

**Comment by mlutegar** [comment]
**Resumo das Funcionalidades:**

1. **Strava:**
   - **Monitoramento de Atividades:** Suporte para corrida, ciclismo, caminhada e outras atividades. Inclui rastreamento via GPS, tempo, distância, ritmo, elevação e calorias queimadas.
   - **Social Features:** Rede social robusta, permitindo que os usuários compartilhem atividades, sigam amigos e participem de desafios. "Segments" permitem competir em rotas populares.
   - **Integração:** Compatível com uma vasta gama de dispositivos como relógios GPS, monitores de frequência cardíaca e outros.
   - **Premium (Strava Summit):** Oferece recursos adicionais, como análise detalhada de desempenho, planos de treinamento e recuperação avançada.

2. **RunKeeper:**
   - **Monitoramento de Atividades:** Foco em corridas e caminhadas, com rastreamento via GPS e informações detalhadas sobre distância, tempo, ritmo e calorias.
   - **Planos de Treinamento:** Personalização de planos de treino baseados em metas específicas (perda de peso, corridas de longa distância, etc.).
   - **Social Features:** Permite adicionar amigos e participar de desafios. Possui funcionalidades para compartilhamento de progresso em redes sociais.
   - **Integração:** Compatível com vários dispositivos de monitoramento e fones de ouvido Bluetooth para áudio guiado.

3. **Nike Run Club:**
   - **Monitoramento de Atividades:** Foco em corridas, com suporte para GPS, ritmo, tempo, distância e calorias.
   - **Treinos Guiados:** Oferece uma ampla gama de treinos guiados por áudio, desde iniciantes até corredores avançados, incluindo programas personalizados.
   - **Social Features:** Conecta-se com amigos e permite competições semanais e mensais. Possui integração com a comunidade global Nike.
   - **Conquistas e Motivação:** Oferece troféus e badges para motivação, além de feedback personalizado após cada corrida.

**Comment by marcelosm22** [comment]
*Resumo das Funcionalidades:*

1. *Strava:*
   - *Monitoramento de Atividades:* Suporte para corrida, ciclismo, caminhada e outras atividades. Inclui rastreamento via GPS, tempo, distância, ritmo, elevação e calorias queimadas.
   - *Social Features:* Rede social robusta, permitindo que os usuários compartilhem atividades, sigam amigos e participem de desafios. "Segments" permitem competir em rotas populares.
   - *Integração:* Compatível com uma vasta gama de dispositivos como relógios GPS, monitores de frequência cardíaca e outros.
   - *Premium (Strava Summit):* Oferece recursos adicionais, como análise detalhada de desempenho, planos de treinamento e recuperação avançada.

2. *RunKeeper:*
   - *Monitoramento de Atividades:* Foco em corridas e caminhadas, com rastreamento via GPS e informações detalhadas sobre distância, tempo, ritmo e calorias.
   - *Planos de Treinamento:* Personalização de planos de treino baseados em metas específicas (perda de peso, corridas de longa distância, etc.).
   - *Social Features:* Permite adicionar amigos e participar de desafios. Possui funcionalidades para compartilhamento de progresso em redes sociais.
   - *Integração:* Compatível com vários dispositivos de monitoramento e fones de ouvido Bluetooth para áudio guiado.

3. *Nike Run Club:*
   - *Monitoramento de Atividades:* Foco em corridas, com suporte para GPS, ritmo, tempo, distância e calorias.
   - *Treinos Guiados:* Oferece uma ampla gama de treinos guiados por áudio, desde iniciantes até corredores avançados, incluindo programas personalizados.
   - *Social Features:* Conecta-se com amigos e permite competições semanais e mensais. Possui integração com a comunidade global Nike.
   - *Conquistas e Motivação:* Oferece troféus e badges para motivação, além de feedback personalizado após cada corrida.
